version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: school_platform_db_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: school_platform_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts:/scripts
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
